# Generated by Django 5.2.17 on 2026-08-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше число — выше на странице.', verbose_name='порядок')),
                ('title', models.CharField(max_length=150, verbose_name='название направления')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='адрес в ссылке')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_team_practice', models.BooleanField(default=False, help_text='Отметьте для направлений, которые вы ведёте в команде. На сайте появится соответствующая пометка.', verbose_name='веду вместе с коллегами')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше число — выше на странице.', verbose_name='порядок')),
                ('title', models.CharField(max_length=200, verbose_name='название услуги')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='адрес в ссылке')),
                ('short_description', models.CharField(blank=True, help_text='Одна строка под названием.', max_length=300, verbose_name='коротко')),
                ('description', models.TextField(blank=True, verbose_name='подробное описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена')),
                ('price_prefix', models.CharField(blank=True, choices=[('', 'точная цена'), ('от', 'от'), ('до', 'до')], default='', max_length=10, verbose_name='приставка к цене')),
                ('currency', models.CharField(default='₪', max_length=10, verbose_name='валюта')),
                ('price_note', models.CharField(blank=True, help_text='Например: за консультацию, за час, по договорённости.', max_length=120, verbose_name='примечание к цене')),
                ('is_free', models.BooleanField(default=False, verbose_name='бесплатно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order', 'id'],
            },
        ),
    ]
