# Generated by Django 5.2.17 on 2026-08-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='currency',
        ),
    ]
