# Generated by Django 5.2.17 on 2026-08-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше число — выше на странице.', verbose_name='порядок')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='кем выдано')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='год')),
            ],
            options={
                'verbose_name': 'образование и допуски',
                'verbose_name_plural': 'Образование и допуски',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше число — выше на странице.', verbose_name='порядок')),
                ('period', models.CharField(help_text='Например: 2019 — сейчас', max_length=50, verbose_name='период')),
                ('title', models.CharField(max_length=200, verbose_name='должность или роль')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='место')),
                ('description', models.TextField(blank=True, verbose_name='что делала')),
            ],
            options={
                'verbose_name': 'запись об опыте',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('full_name', models.CharField(default='Имя Фамилия', max_length=150, verbose_name='имя и фамилия')),
                ('role', models.CharField(default='Юрист по трудовому праву', max_length=150, verbose_name='кто вы')),
                ('hero_title', models.CharField(default='Разберёмся, что происходит на вашей работе', max_length=200, verbose_name='заголовок на первом экране')),
                ('hero_subtitle', models.TextField(blank=True, default='Выберите вопрос, который ближе всего к вашей ситуации. Формулировать ничего не нужно — я перезвоню и уточню детали сама.', verbose_name='подзаголовок на первом экране')),
                ('about', models.TextField(blank=True, help_text='Обычный текст. Пустая строка разделяет абзацы.', verbose_name='о себе')),
                ('photo', models.ImageField(blank=True, upload_to='site/', verbose_name='фотография')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('telegram', models.CharField(blank=True, help_text='Без @, например: anna_law', max_length=100, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, help_text='Только цифры, например: 972501234567', max_length=50, verbose_name='WhatsApp')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город')),
                ('working_hours', models.CharField(blank=True, max_length=150, verbose_name='часы приёма')),
                ('response_promise', models.CharField(blank=True, default='Отвечаю в течение рабочего дня', max_length=150, verbose_name='обещание по времени ответа')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='описание для поисковиков')),
                ('privacy_policy', models.TextField(blank=True, help_text='Показывается на отдельной странице, ссылка есть в форме заявки.', verbose_name='текст политики обработки данных')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
