# Generated by Django 5.2.17 on 2026-08-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='₽', help_text='Символ или код: ₽, ₪, $, €, USD. Применяется ко всем ценам.', max_length=10, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency_before_price',
            field=models.BooleanField(default=False, help_text='Включите для $ и €: получится «$1500» вместо «1500 $».', verbose_name='символ перед суммой'),
        ),
    ]
