# Generated by Django 5.2.17 on 2026-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='scan',
            field=models.ImageField(blank=True, help_text='Изображение (jpg или png). Перед загрузкой закрасьте номер документа и другие личные данные — файл будет доступен всем.', upload_to='credentials/', verbose_name='скан документа'),
        ),
        migrations.AddField(
            model_name='credential',
            name='show_scan',
            field=models.BooleanField(default=False, help_text='Снимите галочку, чтобы файл остался в базе, но исчез со страницы.', verbose_name='показывать скан на сайте'),
        ),
    ]
