# Generated by Django 5.2.17 on 2026-08-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше число — выше на странице.', verbose_name='порядок')),
                ('text', models.CharField(help_text='Формулировка от лица клиента. Например: «Мне не оплатили сверхурочные».', max_length=200, verbose_name='вопрос')),
                ('hint', models.CharField(blank=True, help_text='Короткое пояснение под вопросом. Необязательно.', max_length=200, verbose_name='подсказка')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_templates', to='services.service', verbose_name='связанная услуга')),
            ],
            options={
                'verbose_name': 'готовый вопрос',
                'verbose_name_plural': 'Готовые вопросы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('contact', models.CharField(max_length=150, verbose_name='контакт')),
                ('contact_method', models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Почта')], default='phone', max_length=20, verbose_name='способ связи')),
                ('custom_question', models.TextField(blank=True, verbose_name='свой вопрос')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('spam', 'Спам')], db_index=True, default='new', max_length=20, verbose_name='статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='заметка для себя')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='браузер')),
                ('source_page', models.CharField(blank=True, max_length=300, verbose_name='страница отправки')),
                ('question_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.questiontemplate', verbose_name='выбранный вопрос')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
